### ISSUE TITLE
AMCDriver - IgnitionFileExport - Import  failing 

### ISSUE THREAD

**Issue by leovac** [aws-quickstart/quickstart-aws-industrial-machine-connectivity#46]
Installed GGC and  Ignition (Data Flow Option 1) with  IMC  guide  on a physical device. 
On step 4. [after deployment](https://github.com/aws-quickstart/quickstart-aws-industrial-machine-connectivity/blob/main/assets/readme/ignition.md) exported the  the tags in json file:
[tags-export.txt](https://github.com/aws-quickstart/quickstart-aws-industrial-machine-connectivity/files/6511920/tags-export.txt)
 
Upladed  the tag in S3 bucket as  described in step 5. But the Lamda fails with this error: 

`[ERROR] KeyError: 'tags'

Traceback (most recent call last):
  File "/var/task/assetModelConverter.py", line 185, in handler
    assetModelClass.processEvent(event)
  File "/var/task/assetModelConverter.py", line 167, in processEvent
    driver.processEvent(birthEvent)
  File "/var/task/drivers/ignitionFileDriver.py", line 322, in processEvent
    self.processBirthObjects(event['birthData'])
  File "/var/task/drivers/ignitionFileDriver.py", line 117, in processBirthObjects
    for modelTag in record['tags']:
`
Tried out with 2 different tag  exports, one from working virtual installation and the other from physical deployment. 

Please help....

**Comment by leovac** [comment]
> Installed GGC and Ignition (Data Flow Option 1) with IMC guide on a physical device.
> On step 4. [after deployment](https://github.com/aws-quickstart/quickstart-aws-industrial-machine-connectivity/blob/main/assets/readme/ignition.md) exported the the tags in json file:
> [tags-export.txt](https://github.com/aws-quickstart/quickstart-aws-industrial-machine-connectivity/files/6511920/tags-export.txt)
> 
> Upladed the tags json file in S3 bucket as described in step 5. But the Lamda fails with this error:
> 
> `[ERROR] KeyError: 'tags'
> 
> Traceback (most recent call last):
>   File "/var/task/assetModelConverter.py", line 185, in handler
>     assetModelClass.processEvent(event)
>   File "/var/task/assetModelConverter.py", line 167, in processEvent
>     driver.processEvent(birthEvent)
>   File "/var/task/drivers/ignitionFileDriver.py", line 322, in processEvent
>     self.processBirthObjects(event['birthData'])
>   File "/var/task/drivers/ignitionFileDriver.py", line 117, in processBirthObjects
>     for modelTag in record['tags']:
> `
> Tried out with 2 different tag exports, one from working virtual installation and the other from physical deployment.
> 
> Please help....

The root cause of the problem is tha data  types and hierarchy in ignition was not created during IMC deployment on physical hardware.   In the virtual deployment everything was created as  expected. 
The hack is to export  virtual deployment ignition dataTypes and imported it in the physical one with Ignition designer to avoid manual creation.

**Comment by ashok-rao** [comment]
@sshvans , any thoughts around this please?

**Comment by sshvans** [comment]
@TensorIoT-Shahan ☝️ can you help?

**Comment by TensorIoT-Shahan** [comment]
@leovac, it sounds like you were able to get the import working (albiet taking the data types/hierarchy from a virtual deployment's Ignition server), is that correct? Or are you still blocked on this issue?

Regardless, it sounds like the documentation around what is required in the Ignition hierarchy for the file to be accepted by the Asset Model Converter can be altered/improved.

**Comment by leovac** [comment]
Yes I'm able to do the workaround: 
1. Export tags & types from virtual deployment
2. Import to physical deployment
3. Refresh mqqt providers
